# Generated by Django 4.1.5 on 2023-10-12 23:43

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keywords', models.CharField(blank=True, max_length=300, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('Image', models.FileField(blank=True, null=True, upload_to='files/images/Category/%Y/%m/%d/')),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('stock_no', models.IntegerField(default=0)),
                ('side_one', models.FileField(blank=True, null=True, upload_to='files/images/Item/%Y/%m/%d/')),
                ('side_two', models.FileField(blank=True, null=True, upload_to='files/images/Item/%Y/%m/%d/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity1', models.IntegerField(default=0)),
                ('quantity2', models.IntegerField(default=0)),
                ('quantity3', models.IntegerField(default=0)),
                ('discount_price1', models.FloatField(blank=True, null=True)),
                ('discount_price2', models.FloatField(blank=True, null=True)),
                ('discount_price3', models.FloatField(blank=True, null=True)),
                ('description_short', models.CharField(max_length=50)),
                ('description_long', models.TextField()),
                ('keywords', models.CharField(blank=True, max_length=300, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField()),
                ('Image1', models.FileField(blank=True, null=True, upload_to='files/images/Item/%Y/%m/%d/')),
                ('Image2', models.FileField(blank=True, null=True, upload_to='files/images/Item/%Y/%m/%d/')),
                ('Image3', models.FileField(blank=True, null=True, upload_to='files/images/Item/%Y/%m/%d/')),
                ('Image4', models.FileField(blank=True, null=True, upload_to='files/images/Item/%Y/%m/%d/')),
                ('Image5', models.FileField(blank=True, null=True, upload_to='files/images/Item/%Y/%m/%d/')),
                ('Image6', models.FileField(blank=True, null=True, upload_to='files/images/Item/%Y/%m/%d/')),
                ('video_link1', models.CharField(blank=True, max_length=300, null=True)),
                ('video_link2', models.CharField(blank=True, max_length=300, null=True)),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='Ecommerce.category')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption1', models.CharField(max_length=100)),
                ('caption2', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('image', models.ImageField(help_text='Size: 1920x570', upload_to='')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderItem', to='Ecommerce.item')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('companyname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('emailaddress', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('shipping_address', models.CharField(max_length=500)),
                ('apartment_address', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=100)),
                ('session_key', models.CharField(max_length=100)),
                ('default', models.BooleanField(default=False)),
                ('item', models.ManyToManyField(blank=True, to='Ecommerce.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='CardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.item')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('keywords', models.CharField(blank=True, max_length=300, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='files/images/Blog/Image/%Y/%m/%d/')),
                ('Titel', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('slideImage', models.FileField(blank=True, null=True, upload_to='files/images/Blog/slideImage/%Y/%m/%d/')),
                ('slideVideo', models.CharField(blank=True, max_length=300, null=True)),
                ('body', ckeditor.fields.RichTextField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Blog', to='Ecommerce.category')),
            ],
        ),
    ]
