# Generated by Django 4.1.5 on 2023-10-14 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0002_howitwork_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='howitwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='Ecommerce.howitwork'),
        ),
        migrations.AddField(
            model_name='item',
            name='questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='Ecommerce.questions'),
        ),
    ]
