# Generated by Django 4.1.5 on 2023-10-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0003_item_howitwork_item_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='top_slider_mobile',
            field=models.FileField(blank=True, null=True, upload_to='files/images/Item/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='item',
            name='top_slider_video',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='top_spider_web',
            field=models.FileField(blank=True, null=True, upload_to='files/images/Item/%Y/%m/%d/'),
        ),
    ]
