# Generated by Django 4.1.5 on 2023-10-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0004_item_top_slider_mobile_item_top_slider_video_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='top_spider_web',
            new_name='top_slider_web',
        ),
        migrations.AddField(
            model_name='item',
            name='long_image',
            field=models.FileField(blank=True, null=True, upload_to='files/images/long/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='side_one',
            field=models.FileField(blank=True, null=True, upload_to='files/images/side_one/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='side_two',
            field=models.FileField(blank=True, null=True, upload_to='files/images/side_one/%Y/%m/%d/'),
        ),
    ]
