# Generated by Django 4.1.5 on 2023-10-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0005_rename_top_spider_web_item_top_slider_web_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='howitwork',
        ),
        migrations.RemoveField(
            model_name='item',
            name='questions',
        ),
        migrations.AddField(
            model_name='item',
            name='howitwork',
            field=models.ManyToManyField(blank=True, to='Ecommerce.howitwork'),
        ),
        migrations.AddField(
            model_name='item',
            name='questions',
            field=models.ManyToManyField(blank=True, to='Ecommerce.questions'),
        ),
    ]
