# Generated by Django 4.1.5 on 2023-10-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0006_remove_item_howitwork_remove_item_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description_long_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description_long_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description_short_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description_short_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='keywords_ar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='keywords_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='title_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
