# Generated by Django 4.1.5 on 2023-10-14 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0008_rename_description_long_ar_item_description_long_e_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='description_long_e',
            new_name='description_long_ar',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='description_long_n',
            new_name='description_long_en',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='description_short_e',
            new_name='description_short_ar',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='description_short_n',
            new_name='description_short_en',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='keywords_e',
            new_name='keywords_ar',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='keywords_n',
            new_name='keywords_en',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='title_e',
            new_name='title_ar',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='title_n',
            new_name='title_en',
        ),
    ]
