# Generated by Django 4.1.5 on 2023-10-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0009_rename_description_long_e_item_description_long_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Orderـstatus',
            field=models.CharField(choices=[('waiting', 'انتظار'), ('Orderـprocessing', 'تم تقديم الخدمة'), ('Shipping', 'تم الشحن'), ('Order_done', 'تم'), ('Service_done', 'تم تقديم الخدمة')], default='انتظار', max_length=20),
        ),
    ]
