# Generated by Django 4.1.5 on 2023-10-15 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0011_alter_order_orderـstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='anticipation',
            field=models.CharField(blank=True, choices=[('mon', 'الاثنين'), ('tue', 'الثلاثاء'), ('wed', 'الأربعاء'), ('thu', 'الخميس'), ('fri', 'الجمعة'), ('sat', 'السبت'), ('sun', 'الأحد')], max_length=20, null=True),
        ),
    ]
