# Generated by Django 4.1.5 on 2023-10-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0012_order_anticipation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Tracking',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
