# Generated by Django 4.1.5 on 2023-10-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0013_order_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Orderـstatus',
            field=models.CharField(choices=[('waiting', 'انتظار'), ('Orderـprocessing', 'تجهيز الطلب'), ('Shipping', 'تم الشحن'), ('Order_done', 'تم'), ('cancel', 'الغاء')], default='انتظار', max_length=20),
        ),
    ]
