# Generated by Django 4.1.5 on 2023-10-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0014_alter_order_orderـstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(blank=True, max_length=300, null=True)),
                ('FaviconIco', models.FileField(blank=True, null=True, upload_to='files/images/FaviconIco/%Y/%m/%d/')),
                ('logo', models.FileField(blank=True, null=True, upload_to='files/images/logo/%Y/%m/%d/')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('PHONE', models.CharField(blank=True, max_length=15, null=True)),
                ('Whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('linkedinlinke', models.CharField(blank=True, max_length=500, null=True)),
                ('snapchat', models.CharField(blank=True, max_length=300, null=True)),
                ('instagramlinke', models.CharField(blank=True, max_length=300, null=True)),
                ('Twitterlinke', models.CharField(blank=True, max_length=300, null=True)),
                ('facebooklinke', models.CharField(blank=True, max_length=300, null=True)),
                ('Map_Address', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='silderImage',
            field=models.FileField(blank=True, null=True, upload_to='files/images/silderImage/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_long',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_long_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_long_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_short',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_short_ar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_short_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
