# Generated by Django 4.1.5 on 2023-10-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0015_info_category_silderimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='silderImage',
        ),
        migrations.AddField(
            model_name='category',
            name='top_slider_mobile',
            field=models.FileField(blank=True, null=True, upload_to='files/images/Item/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='category',
            name='top_slider_web',
            field=models.FileField(blank=True, null=True, upload_to='files/images/Item/%Y/%m/%d/'),
        ),
    ]
