# Generated by Django 4.1.5 on 2023-10-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0018_category_description_ar_category_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=300, null=True)),
                ('answer', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
