# Generated by Django 4.1.5 on 2023-10-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0019_questionsgeneral'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsgeneral',
            name='answer_ar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='questionsgeneral',
            name='answer_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='questionsgeneral',
            name='question_ar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='questionsgeneral',
            name='question_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
