# Generated by Django 4.1.5 on 2023-10-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0020_questionsgeneral_answer_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='caption1',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='caption1_ar',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='caption1_en',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='caption2',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='caption2_ar',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='caption2_en',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='image',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='link',
        ),
        migrations.AddField(
            model_name='slide',
            name='top_slider_mobile',
            field=models.FileField(blank=True, null=True, upload_to='files/images/Item/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='slide',
            name='top_slider_web',
            field=models.FileField(blank=True, null=True, upload_to='files/images/Item/%Y/%m/%d/'),
        ),
    ]
