# Generated by Django 4.1.5 on 2023-10-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0021_remove_slide_caption1_remove_slide_caption1_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount_price1',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_price2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_price3',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
