# Generated by Django 4.1.5 on 2023-10-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0023_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Orderـstatus',
            field=models.CharField(choices=[('waiting', 'انتظار'), ('Orderprocessing', 'تجهيز الطلب'), ('Shipping', 'تم الشحن'), ('Orderdone', 'تم'), ('cancel', 'الغاء')], default='انتظار', max_length=20),
        ),
    ]
