# Generated by Django 4.1.5 on 2023-10-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0029_alter_blog_slug_alter_category_slug_alter_item_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shipping_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='info',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
