# Generated by Django 4.1.5 on 2023-10-22 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0030_country_info_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_order', to='Ecommerce.country'),
        ),
    ]
