# Generated by Django 4.1.5 on 2023-10-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0031_alter_order_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='tax',
        ),
        migrations.AddField(
            model_name='country',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
