# Generated by Django 4.1.5 on 2023-10-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0032_remove_info_tax_country_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='tax',
            field=models.IntegerField(default=0),
        ),
    ]
