# Generated by Django 4.1.5 on 2023-10-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0034_basetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetext',
            name='questions',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
