# Generated by Django 4.1.5 on 2023-10-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0036_alter_basetext_date_alter_basetext_paid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaseText',
            new_name='BaseTextTranslate',
        ),
    ]
