# Generated by Django 4.1.5 on 2023-10-23 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0039_basetexttranslate_date_basetexttranslate_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basetexttranslate',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='basetexttranslate',
            name='Paid',
        ),
        migrations.RemoveField(
            model_name='basetexttranslate',
            name='add_New_Category',
        ),
        migrations.RemoveField(
            model_name='basetexttranslate',
            name='add_new_product',
        ),
        migrations.RemoveField(
            model_name='basetexttranslate',
            name='available_Quantity',
        ),
        migrations.RemoveField(
            model_name='basetexttranslate',
            name='buy_Now',
        ),
        migrations.RemoveField(
            model_name='basetexttranslate',
            name='cancel',
        ),
        migrations.RemoveField(
            model_name='basetexttranslate',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='basetexttranslate',
            name='delete_this',
        ),
        migrations.RemoveField(
            model_name='basetexttranslate',
            name='go_Shopping',
        ),
        migrations.RemoveField(
            model_name='basetexttranslate',
            name='help_you',
        ),
        migrations.RemoveField(
            model_name='basetexttranslate',
            name='learn_More',
        ),
        migrations.RemoveField(
            model_name='basetexttranslate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='basetexttranslate',
            name='no_available',
        ),
        migrations.RemoveField(
            model_name='basetexttranslate',
            name='not_Paid',
        ),
        migrations.RemoveField(
            model_name='basetexttranslate',
            name='number_of_Orders',
        ),
        migrations.RemoveField(
            model_name='basetexttranslate',
            name='proceed_to_Payment',
        ),
        migrations.RemoveField(
            model_name='basetexttranslate',
            name='questions_help',
        ),
        migrations.RemoveField(
            model_name='basetexttranslate',
            name='save',
        ),
        migrations.RemoveField(
            model_name='basetexttranslate',
            name='shipping_information',
        ),
        migrations.RemoveField(
            model_name='basetexttranslate',
            name='shop_our_various',
        ),
        migrations.RemoveField(
            model_name='basetexttranslate',
            name='stockout',
        ),
        migrations.RemoveField(
            model_name='basetexttranslate',
            name='total',
        ),
        migrations.RemoveField(
            model_name='basetexttranslate',
            name='update',
        ),
        migrations.RemoveField(
            model_name='basetexttranslate',
            name='view_Order',
        ),
    ]
