# Generated by Django 4.1.5 on 2023-10-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0040_remove_basetexttranslate_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='moreTextTranslate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockout', models.CharField(blank=True, max_length=50, null=True)),
                ('buy_Now', models.CharField(blank=True, max_length=50, null=True)),
                ('learn_More', models.CharField(blank=True, max_length=50, null=True)),
                ('help_you', models.CharField(blank=True, max_length=50, null=True)),
                ('add_new_product', models.CharField(blank=True, max_length=50, null=True)),
                ('add_New_Category', models.CharField(blank=True, max_length=50, null=True)),
                ('update', models.CharField(blank=True, max_length=50, null=True)),
                ('save', models.CharField(blank=True, max_length=50, null=True)),
                ('delete', models.CharField(blank=True, max_length=50, null=True)),
                ('cancel', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_Orders', models.CharField(blank=True, max_length=50, null=True)),
                ('Date', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('Paid', models.CharField(blank=True, max_length=50, null=True)),
                ('not_Paid', models.CharField(blank=True, max_length=50, null=True)),
                ('view_Order', models.CharField(blank=True, max_length=50, null=True)),
                ('delete_this', models.CharField(blank=True, max_length=50, null=True)),
                ('available_Quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('no_available', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_information', models.CharField(blank=True, max_length=50, null=True)),
                ('proceed_to_Payment', models.CharField(blank=True, max_length=50, null=True)),
                ('go_Shopping', models.CharField(blank=True, max_length=50, null=True)),
                ('shop_our_various', models.CharField(blank=True, max_length=50, null=True)),
                ('questions_help', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
