# Generated by Django 4.1.5 on 2023-10-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0041_moretexttranslate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackTextTranslate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_Category', models.CharField(blank=True, max_length=50, null=True)),
                ('track_help', models.CharField(blank=True, max_length=50, null=True)),
                ('track_but', models.CharField(blank=True, max_length=50, null=True)),
                ('order_number', models.CharField(blank=True, max_length=50, null=True)),
                ('track_your_order', models.CharField(blank=True, max_length=50, null=True)),
                ('order_status', models.CharField(blank=True, max_length=50, null=True)),
                ('processing', models.CharField(blank=True, max_length=50, null=True)),
                ('shipped', models.CharField(blank=True, max_length=50, null=True)),
                ('arrival_day', models.CharField(blank=True, max_length=50, null=True)),
                ('Order_delivered', models.CharField(blank=True, max_length=50, null=True)),
                ('cancelled', models.CharField(blank=True, max_length=50, null=True)),
                ('Saturday', models.CharField(blank=True, max_length=50, null=True)),
                ('Sunday', models.CharField(blank=True, max_length=50, null=True)),
                ('Monday', models.CharField(blank=True, max_length=50, null=True)),
                ('Tuesday', models.CharField(blank=True, max_length=50, null=True)),
                ('Wednesday', models.CharField(blank=True, max_length=50, null=True)),
                ('Thursday', models.CharField(blank=True, max_length=50, null=True)),
                ('Friday', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='moretexttranslate',
            old_name='questions_help',
            new_name='shipping',
        ),
        migrations.RenameField(
            model_name='moretexttranslate',
            old_name='shop_our_various',
            new_name='subtotal',
        ),
        migrations.AddField(
            model_name='moretexttranslate',
            name='xat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
