# Generated by Django 4.1.5 on 2023-10-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0042_tracktexttranslate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTextTranslate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_information', models.CharField(blank=True, max_length=50, null=True)),
                ('order_number', models.CharField(blank=True, max_length=50, null=True)),
                ('Paid', models.CharField(blank=True, max_length=50, null=True)),
                ('not_Paid', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_information', models.CharField(blank=True, max_length=50, null=True)),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('Quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.CharField(blank=True, max_length=50, null=True)),
                ('subtotal', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping', models.CharField(blank=True, max_length=50, null=True)),
                ('tax', models.CharField(blank=True, max_length=50, null=True)),
                ('total_all', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='moretexttranslate',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='moretexttranslate',
            name='Paid',
        ),
        migrations.RemoveField(
            model_name='moretexttranslate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='moretexttranslate',
            name='not_Paid',
        ),
        migrations.RemoveField(
            model_name='moretexttranslate',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='moretexttranslate',
            name='shipping_information',
        ),
        migrations.RemoveField(
            model_name='moretexttranslate',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='moretexttranslate',
            name='total',
        ),
        migrations.RemoveField(
            model_name='moretexttranslate',
            name='xat',
        ),
    ]
