# Generated by Django 4.1.5 on 2023-10-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0043_invoicetexttranslate_remove_moretexttranslate_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetexttranslate',
            name='pay_help',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
