# Generated by Django 4.1.5 on 2023-10-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0044_invoicetexttranslate_pay_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetexttranslate',
            name='items',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
