# Generated by Django 4.1.5 on 2023-10-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0045_basetexttranslate_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetexttranslate',
            name='invoic_help',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
