# Generated by Django 4.1.5 on 2023-10-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0046_invoicetexttranslate_invoic_help'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moretexttranslate',
            name='available_Quantity',
        ),
        migrations.RemoveField(
            model_name='moretexttranslate',
            name='go_Shopping',
        ),
        migrations.RemoveField(
            model_name='moretexttranslate',
            name='no_available',
        ),
        migrations.RemoveField(
            model_name='moretexttranslate',
            name='proceed_to_Payment',
        ),
    ]
