# Generated by Django 4.1.5 on 2023-10-24 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0047_remove_moretexttranslate_available_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moretexttranslate',
            name='cancel',
        ),
        migrations.RemoveField(
            model_name='moretexttranslate',
            name='delete_this',
        ),
        migrations.RemoveField(
            model_name='moretexttranslate',
            name='number_of_Orders',
        ),
        migrations.RemoveField(
            model_name='moretexttranslate',
            name='view_Order',
        ),
    ]
