# Generated by Django 4.1.5 on 2023-10-24 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0048_remove_moretexttranslate_cancel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moretexttranslate',
            name='add_New_Category',
        ),
        migrations.RemoveField(
            model_name='moretexttranslate',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='moretexttranslate',
            name='save',
        ),
        migrations.RemoveField(
            model_name='moretexttranslate',
            name='update',
        ),
    ]
