# Generated by Django 4.1.5 on 2023-10-24 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0049_remove_moretexttranslate_add_new_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracktexttranslate',
            old_name='help_Category',
            new_name='waiting',
        ),
    ]
