# Generated by Django 4.1.5 on 2023-10-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0050_rename_help_category_tracktexttranslate_waiting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTextTranslate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('howitـworks', models.CharField(blank=True, max_length=50, null=True)),
                ('Buyـmore', models.CharField(blank=True, max_length=100, null=True)),
                ('discount', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('Quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('Category', models.CharField(blank=True, max_length=50, null=True)),
                ('Addـtoـcart', models.CharField(blank=True, max_length=50, null=True)),
                ('questionsanswered', models.CharField(blank=True, max_length=50, null=True)),
                ('make_purchase', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
