# Generated by Django 4.1.5 on 2023-10-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0051_itemtexttranslate'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtexttranslate',
            name='Notـavailable',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itemtexttranslate',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
