# Generated by Django 4.1.5 on 2023-10-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0052_itemtexttranslate_notـavailable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moretexttranslate',
            name='go_Payment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='moretexttranslate',
            name='go_Shopping',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
