# Generated by Django 4.1.5 on 2023-10-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0053_moretexttranslate_go_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moretexttranslate',
            name='help_Payment',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
