# Generated by Django 4.1.5 on 2023-10-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0054_moretexttranslate_help_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetexttranslate',
            name='save_order_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoicetexttranslate',
            name='you_can',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoicetexttranslate',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
