# Generated by Django 4.1.5 on 2023-10-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0055_invoicetexttranslate_save_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetexttranslate',
            name='track_order_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoicetexttranslate',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
