# Generated by Django 4.1.5 on 2023-10-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0056_invoicetexttranslate_track_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetexttranslate',
            name='prin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
