# Generated by Django 4.1.5 on 2023-10-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0059_basetexttranslate_all_categories_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetexttranslate',
            name='logout',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
