# Generated by Django 4.1.5 on 2023-10-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0060_basetexttranslate_logout'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetexttranslate',
            name='logout_ar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='basetexttranslate',
            name='logout_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
