# Generated by Django 4.1.5 on 2023-10-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0061_basetexttranslate_logout_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetexttranslate',
            name='help_categories',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
