# Generated by Django 4.1.5 on 2023-10-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0063_basetexttranslate_help_categories_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_ar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='price_en',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
