# Generated by Django 4.1.5 on 2023-10-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0064_item_price_ar_item_price_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='shipping_price_ar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='shipping_price_en',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
